# Generated by Django 2.2 on 2020-07-01 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compound',
            old_name='InChl',
            new_name='InChI',
        ),
        migrations.RenameField(
            model_name='compound',
            old_name='InChlKey',
            new_name='InChIKey',
        ),
    ]
