# Generated by Django 2.2 on 2020-07-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200702_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdb',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gene', models.CharField(max_length=500, null=True)),
                ('pdb', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
