# Generated by Django 2.2 on 2020-07-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdb',
            name='data',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pdb',
            name='method',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
