# Generated by Django 2.2 on 2020-07-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200730_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdb',
            old_name='data',
            new_name='date',
        ),
    ]
