# Generated by Django 2.2 on 2020-07-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200730_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='prop',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
