# Generated by Django 3.0.8 on 2020-08-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_gene_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='go0',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gene',
            name='goterm0',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='go',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='goterm',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
