# Generated by Django 2.2 on 2020-08-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200814_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdb',
            name='uniprot',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
