# Generated by Django 2.2 on 2020-08-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_pdb_uniprot'),
    ]

    operations = [
        migrations.CreateModel(
            name='figc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gene', models.CharField(max_length=500, null=True)),
                ('number', models.IntegerField(null=True)),
                ('level', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='figd',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gene', models.CharField(max_length=500, null=True)),
                ('number', models.IntegerField(null=True)),
                ('level', models.IntegerField(null=True)),
            ],
        ),
    ]
