# Generated by Django 2.2 on 2020-08-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_figc_figd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figc',
            name='number',
            field=models.FloatField(null=True),
        ),
    ]
