# Generated by Django 2.2 on 2020-08-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200827_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figd',
            name='number',
            field=models.FloatField(null=True),
        ),
    ]
