# Generated by Django 3.0.8 on 2020-08-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200827_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='figc',
            name='factor',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='figd',
            name='factor',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='figc',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='figd',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
