# Generated by Django 3.0.8 on 2020-11-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_gene_pmid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='pmid',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
