# Generated by Django 3.0.8 on 2021-01-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20201113_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
