# Generated by Django 3.0.8 on 2021-01-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_compound_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compound',
            old_name='url',
            new_name='md5',
        ),
    ]
